config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "lists#index"
  resources :lists do
    resources :bookmarks, only: [:new, :create, :destroy]
  end

  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: "and list pairing must be unique" }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, uniqueness:true, presence: true

end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness:true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = @list.bookmarks.build(bookmark_params)

    if @bookmark.save
      redirect_to lists_path(@list), notice: 'Bookmark was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), notice: 'Bookmark was successfully deleted.'
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      # Redireciona para a página da lista criada
      redirect_to @list, notice: 'List was successfully created.'
    else
      # Renderiza o formulário novamente caso haja erro
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    @list.update(list_params)
    redirect_to
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to @list, notice: "List was updated sucessfully!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, notice: 'Movie was successfully deleted.'
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>Add a Bookmark to <%= @list.name %></h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <div class="form-group">
    <%= f.input :movie_id, collection: Movie.all, label: "Select a movie", as: :select, include_blank: "Choose a movie" %>
  </div>

  <div class="form-group">
    <%= f.input :comment, as: :text, label: "Comment" %>
  </div>

  <div class="form-group">
    <%= f.button :submit, "Create Bookmark", class: "btn btn-primary" %>
  </div>
<% end %>

<%= link_to "Back to List", list_path(@list), class: "btn btn-secondary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/lists/edit.html.erb
<h1> Edit list </h1>

<%= simple_form_for (@list) do |f| %>
  <%= f.input :name, required: true, placeholder: "Enter the list name" %>
  <%= f.submit "Submit", class: "btn btn-primary" %>

  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
<% end %>

app/views/lists/index.html.erb
<!-- Banner Section --><div class="banner">
  <div class="banner-content">
    <h1 class="display-3 text-center text-white">Welcome to Movie Hub</h1>
    <p class="lead text-center text-white">Create, explore and share your movies lists with your friends.</p>
    <div class="text-center mb-4">
  <%= link_to "New List", new_list_path, class: "btn btn-outline-secondary" %>
</div>
  </div>
</div>


<!-- Display the existing lists -->
<div class="mb-5">
  <h2>Your Lists</h2>
  <ul class="list-group">
    <% @lists.each do |list| %>
      <li class="list-group-item">
        <%= link_to list.name, list_path(list), class: "text-decoration-none" %>
      </li>
    <% end %>
  </ul>
</div>

app/views/lists/new.html.erb
<h1> New List </h1>

<%= simple_form_for (@list) do |f| %>
  <%= f.input :name, required: true, placeholder: "Enter the list name" %>
  <%= f.submit "Submit", class: "btn btn-primary" %>

  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
<% end %>

app/views/lists/show.html.erb
<h2><%= @list.name %></h2>
<div class="bookmarks-container">
  <div class="movies-grid">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="movie-card">
        <div class="movie-poster">
          <%= image_tag(bookmark.movie.poster_url, alt: "#{bookmark.movie.title} Poster", class: "movie-poster-image") if bookmark.movie.poster_url.present? %>
        </div>
        <div class="movie-details">
          <p><strong>Filme:</strong> <%= bookmark.movie.title %></p>
          <p><strong>Comentários:</strong> <%= bookmark.comment %></p>
        </div>
        <%= link_to "Delete", list_bookmark_path(@list, bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove #{bookmark.movie.title} from your #{@list.name} list"}, class: "btn btn-outline-danger" %>
      </div>
    <% end %>
  </div>
</div>



<%= link_to "Add a movie", new_list_bookmark_path(@list), class: "btn btn-outline-secondary"%>

<%= link_to "Return to lists", lists_path, class: "btn btn-outline-secondary"%>

<%= link_to "Edit list", edit_list_path(@list), class: "btn btn-outline-secondary"%>

<%= link_to 'delete', list_path(@list), data: { turbo_method: :delete, turbo_confirm: 'are you sure?'}, class: "btn btn-outline-secondary"%>